name: Testing pipeline

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Building Conda Env
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: prod-env
        environment-file: prod-env.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Test with pytest
      run: |
        pytest tests
      
