name: Testing pipeline

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda deactivate
        conda env remove -n base
        conda env create -f prod-env.yml --name base
        conda activate base
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
