name: Testing pipeline

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Building Conda Env
      uses: conda-incubator/setup-miniconda@v3

    - name: Test with pytest
      run: |
        pytest tests
      with:
        activate-environment: prod-env
        environment-file: prod-env.yml
        python-version: 3.11
        auto-activate-base: false
