name: Testing pipeline

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Debugging
      run: |
        pwd
        ls -a
    - name: Install dependencies
      run: |
        conda env create -f ${{ github.workspace }}/prod-env.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
