name: Recreating Prod Env

on:
  workflow_dispatch:

jobs:
  update-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Prod Environment
      run: |
        conda env create -f start-env.yml
        conda env export --no-builds > prod-env.yml

    - name: Commit Changes
      run: |
        git add prod-env.yml
        git commit -m "Recreated prod-env.yml from start-env.yml"
        git push
