name: Recreating Prod Env

on:
  workflow_dispatch:

jobs:
  update-environment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Recreate Prod Env
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: starter-env
        environment-file: start-env.yml
        python-version: 3.11
        auto-activate-base: false
      run: |
        conda env export --no-builds > prod-env.yml


    - name: Commit Changes
      run: |
        git config --global user.email "palldominiko8@gmail.com"
        git config --global user.name "Daerile"
        
        git add prod-env.yml
        git commit -m "Recreated prod-env.yml from start-env.yml"
        git push
